#!/bin/sh
#
# svgopt -- run scour with custom settings
#

scour                             \
    --disable-style-to-xml        \
    --enable-id-stripping         \
    --nindent=2                   \
    --remove-descriptions         \
    --remove-descriptive-elements \
    --remove-metadata             \
    --remove-titles               \
    --set-precision=3             \
    --shorten-ids "$@"
